
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false
    prefer_single_quotes: true
    avoid_annotating_with_dynamic: true
    depend_on_referenced_packages: false
    always_use_package_imports: true



