name: minapharm_task
description: Minapharm Flutter task

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  equatable: ^2.0.5
  dio: ^4.0.6
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.2.0
  flutter_screenutil: ^5.6.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  json_annotation: ^4.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  formz: ^0.4.1
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  retrofit_generator: ^4.2.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true



